name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js (Frontend & Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Debug: List frontend directory contents
      - name: List Frontend Directory
        working-directory: ./frontend
        run: ls -la

      # Lint Frontend
      - name: Lint Frontend
        working-directory: ./frontend
        run: npm run lint

      # Debug: List backend directory contents
      - name: List Backend Directory
        working-directory: ./backend
        run: ls -la

      # Lint Backend
      - name: Lint Backend
        working-directory: ./backend
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js (Frontend & Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run Tests (Frontend)
        working-directory: ./frontend
        run: npm test

      - name: Run Tests (Backend)
        working-directory: ./backend
        run: npm test
