name: MEAN-CI-pipeline

on: 
  workflow_dispatch:
    inputs:
      Skip-push:
        type: boolean
        description: Skip Docker push
        default: false

jobs: 
  lint-and-test: 
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      # Lint and test backend
      - name: Install dependencies for Backend
        run: |
          cd Backend
          npm ci
      - name: Test Backend
        run: cd Backend && npm run test

      # Lint and test frontend
      - name: Install dependencies for Frontend
        run: |
          cd frontend
          npm ci
      - name: Lint Frontend
        run: npm run lint
        working-directory: ./frontend
      - name: Test Frontend
        run: npm run test
        working-directory: ./frontend

  build-and-push: 
    name: Build and Push to Docker Repository
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps: 
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Build and push the backend Docker image
      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-backend ./backend

      - name: Push Backend Docker Image
        if: ${{ !inputs.Skip-push }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mean-backend

      # Build and push the frontend Docker image
      - name: Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-frontend ./frontend

      - name: Push Frontend Docker Image
        if: ${{ !inputs.Skip-push }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mean-frontend
