name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js (Frontend & Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run ESLint (Frontend)
        working-directory: ./frontend
        run: npx eslint .

      - name: Run ESLint (Backend)
        working-directory: ./backend
        run: npx eslint .
